/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AudioFormat = { 'pcm' : null } |
  { 'pcma' : null } |
  { 'pcmu' : null };
export type CallId = bigint;
export interface CallPreset {
  'id' : bigint,
  'toolsEnabled' : ToolsEnabled,
  'ownerId' : Principal,
  'voice' : Voice,
  'voiceId' : [] | [string],
  'name' : string,
  'sampleRate' : SampleRate,
  'systemPrompt' : string,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
}
export interface CallPresetInput {
  'toolsEnabled' : ToolsEnabled,
  'voice' : Voice,
  'voiceId' : [] | [string],
  'name' : string,
  'sampleRate' : SampleRate,
  'systemPrompt' : string,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
}
export type CallPresetMutationResult = { 'ok' : CallPreset } |
  { 'err' : string };
export type AnsweringPresetStatus = { 'pendingVerification' : null } |
  { 'verified' : null };
export interface AnsweringCaptureOptions {
  'saveTranscript' : boolean,
  'recordAudio' : boolean,
  'consentConfirmed' : boolean,
}
export interface AnsweringPreset {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'phoneNumber' : string,
  'systemPrompt' : string,
  'voice' : Voice,
  'voiceId' : [] | [string],
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
  'sampleRate' : SampleRate,
  'toolsEnabled' : ToolsEnabled,
  'captureOptions' : AnsweringCaptureOptions,
  'enabled' : boolean,
  'verificationStatus' : AnsweringPresetStatus,
  'webhookSecret' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'verifiedAt' : [] | [bigint],
  'lastIncomingAt' : [] | [bigint],
}
export interface AnsweringPresetInput {
  'name' : string,
  'phoneNumber' : string,
  'systemPrompt' : string,
  'voice' : Voice,
  'voiceId' : [] | [string],
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
  'sampleRate' : SampleRate,
  'toolsEnabled' : ToolsEnabled,
  'captureOptions' : AnsweringCaptureOptions,
  'enabled' : boolean,
  'webhookSecret' : string,
}
export type AnsweringPresetMutationResult = { 'ok' : AnsweringPreset } |
  { 'err' : string };
export interface AnsweringLiveSession {
  'sessionId' : string,
  'monitorToken' : string,
  'callSid' : string,
  'userId' : Principal,
  'answeringPresetId' : bigint,
  'answeringPresetName' : string,
  'callerPhone' : string,
  'startedAt' : bigint,
  'allowedSeconds' : bigint,
}
export interface CallRecordPublic {
  'id' : bigint,
  'startTime' : bigint,
  'status' : CallStatus,
  'endTime' : [] | [bigint],
  'userId' : Principal,
  'recipientPhone' : string,
  'callSid' : [] | [string],
  'presetId' : bigint,
  'transcript' : [] | [string],
}
export type CallStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export interface BillingPackage {
  'amountCents' : bigint,
  'id' : string,
  'name' : string,
  'seconds' : bigint,
}
export type BillingMutationResult = { 'ok' : boolean } | { 'err' : string };
export interface BillingStatus {
  'availableSeconds' : bigint,
  'balanceSeconds' : bigint,
  'packages' : Array<BillingPackage>,
  'reservedSeconds' : bigint,
}
export type CallReservationStatus = { 'active' : null } |
  { 'canceled' : null } |
  { 'finished' : null } |
  { 'reserved' : null };
export interface CallReservationPublic {
  'allowedSeconds' : bigint,
  'billedSeconds' : [] | [bigint],
  'callId' : bigint,
  'callSid' : [] | [string],
  'callToken' : [] | [string],
  'canceledReason' : [] | [string],
  'createdAt' : bigint,
  'expiresAt' : bigint,
  'finishedAt' : [] | [bigint],
  'id' : string,
  'presetId' : bigint,
  'recipientPhone' : string,
  'startedAt' : [] | [bigint],
  'status' : CallReservationStatus,
  'transcript' : [] | [string],
  'usedSeconds' : [] | [bigint],
  'user' : Principal,
}
export type CreatePurchaseIntentResult = { 'ok' : PurchaseIntentPublic } |
  { 'err' : string };
export interface InitiateCallInput {
  'recipientPhone' : string,
  'presetId' : bigint,
}
export type InitiateCallResult = {
    'ok' : { 'callSid' : string, 'callId' : bigint }
  } |
  { 'err' : string };
export type PresetId = bigint;
export type PurchaseIntentStatus = { 'canceled' : null } |
  { 'paid' : null } |
  { 'pending' : null };
export interface PurchaseIntentPublic {
  'amountCents' : bigint,
  'createdAt' : bigint,
  'id' : string,
  'mode' : StripeMode,
  'packageId' : string,
  'paidAt' : [] | [bigint],
  'seconds' : bigint,
  'status' : PurchaseIntentStatus,
  'stripeSessionId' : [] | [string],
  'user' : Principal,
}
export type ReserveCallResult = { 'ok' : CallReservationPublic } |
  { 'err' : string };
export type SampleRate = { 'hz16000' : null } |
  { 'hz32000' : null } |
  { 'hz22050' : null } |
  { 'hz24000' : null } |
  { 'hz44100' : null } |
  { 'hz48000' : null } |
  { 'hz8000' : null };
export interface SystemLog {
  'level' : { 'info' : null } |
    { 'warn' : null } |
    { 'error' : null },
  'message' : string,
  'timestamp' : bigint,
  'callId' : [] | [bigint],
}
export interface ToolsEnabled {
  'xSearch' : boolean,
  'webSearch' : boolean,
  'functionCalling' : boolean,
}
export type StripeMode = { 'live' : null } | { 'test' : null };
export interface TurnDetection {
  'prefixPaddingMs' : bigint,
  'threshold' : number,
  'silenceDurationMs' : bigint,
  'serverVad' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface TwilioLine {
  'enabled' : boolean,
  'name' : string,
  'phoneNumber' : string,
}
export interface TwilioLineInput {
  'enabled' : boolean,
  'name' : string,
  'phoneNumber' : string,
}
export type TwilioLineMutationResult = { 'ok' : Array<TwilioLine> } |
  { 'err' : string };
export type Voice = { 'ara' : null } |
  { 'eve' : null } |
  { 'leo' : null } |
  { 'rex' : null } |
  { 'sal' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminAddPromoMinutes' : ActorMethod<
    [Principal, bigint],
    BillingMutationResult
  >,
  'adminGetSystemLogs' : ActorMethod<[bigint], Array<SystemLog>>,
  'adminListAllCalls' : ActorMethod<[], Array<CallRecordPublic>>,
  'adminListUserCalls' : ActorMethod<[Principal], Array<CallRecordPublic>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelCallReservation' : ActorMethod<[string, string], BillingMutationResult>,
  'createAnsweringPreset' : ActorMethod<
    [AnsweringPresetInput],
    AnsweringPresetMutationResult
  >,
  'createPreset' : ActorMethod<[CallPresetInput], CallPreset>,
  'createPurchaseIntent' : ActorMethod<[string], CreatePurchaseIntentResult>,
  'creditPaidSeconds' : ActorMethod<
    [string, string, Principal, bigint, StripeMode],
    BillingMutationResult
  >,
  'deletePreset' : ActorMethod<[PresetId], boolean>,
  'deleteAnsweringPreset' : ActorMethod<[PresetId], boolean>,
  'duplicatePreset' : ActorMethod<[PresetId], [] | [CallPreset]>,
  'finishCallAndDebit' : ActorMethod<
    [string, bigint, [] | [string], [] | [string]],
    BillingMutationResult
  >,
  'getAdminConfig' : ActorMethod<
    [],
    {
      'hasXaiKey' : boolean,
      'hasTwilioAuth' : boolean,
      'twilioFromNumber' : string,
      'twilioAccountSid' : string,
      'twilioPhoneNumbers' : Array<TwilioLine>,
    }
  >,
  'getBillingPackages' : ActorMethod<[], Array<BillingPackage>>,
  'getCallRecord' : ActorMethod<[CallId], [] | [CallRecordPublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getAnsweringPreset' : ActorMethod<[PresetId], [] | [AnsweringPreset]>,
  'getMyBillingStatus' : ActorMethod<[], BillingStatus>,
  'getPreset' : ActorMethod<[PresetId], [] | [CallPreset]>,
  'getPresetForServer' : ActorMethod<[PresetId], [] | [CallPreset]>,
  'getPurchaseIntentForServer' : ActorMethod<
    [string],
    [] | [PurchaseIntentPublic]
  >,
  'getTwilioLineNumbersForServer' : ActorMethod<[], Array<string>>,
  'getAnsweringPresetForServer' : ActorMethod<
    [string, string],
    [] | [AnsweringPreset]
  >,
  'initiateCall' : ActorMethod<[InitiateCallInput], InitiateCallResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyAnsweringLiveSessions' : ActorMethod<
    [],
    Array<AnsweringLiveSession>
  >,
  'listMyAnsweringPresets' : ActorMethod<[], Array<AnsweringPreset>>,
  'listMyCalls' : ActorMethod<[], Array<CallRecordPublic>>,
  'listMyPresets' : ActorMethod<[], Array<CallPreset>>,
  'markReservationStarted' : ActorMethod<[string, string], BillingMutationResult>,
  'removeTwilioLine' : ActorMethod<[string], TwilioLineMutationResult>,
  'reserveCall' : ActorMethod<[InitiateCallInput], ReserveCallResult>,
  'reserveIncomingAnsweringCall' : ActorMethod<
    [string, string, string, string],
    ReserveCallResult
  >,
  'setAdminConfig' : ActorMethod<[string, string, string, string], undefined>,
  'setAnsweringPresetEnabled' : ActorMethod<
    [PresetId, boolean],
    AnsweringPresetMutationResult
  >,
  'setTwilioLine' : ActorMethod<[TwilioLineInput], TwilioLineMutationResult>,
  'setTwilioLineEnabled' : ActorMethod<
    [string, boolean],
    TwilioLineMutationResult
  >,
  'twilioWebhook' : ActorMethod<[string, string], string>,
  'updateCallStatus' : ActorMethod<
    [CallId, CallStatus, [] | [string]],
    boolean
  >,
  'updateAnsweringPreset' : ActorMethod<
    [PresetId, AnsweringPresetInput],
    AnsweringPresetMutationResult
  >,
  'updateAnsweringPresetInstructions' : ActorMethod<
    [PresetId, string],
    AnsweringPresetMutationResult
  >,
  'updatePreset' : ActorMethod<[PresetId, CallPresetInput], [] | [CallPreset]>,
  'updatePresetInstructions' : ActorMethod<
    [PresetId, string],
    CallPresetMutationResult
  >,
  'verifyAnsweringPresetForServer' : ActorMethod<
    [string, string],
    AnsweringPresetMutationResult
  >,
  'registerAnsweringLiveSessionForServer' : ActorMethod<
    [AnsweringLiveSession],
    boolean
  >,
  'finishAnsweringLiveSessionForServer' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
