/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SystemLog = IDL.Record({
  'level' : IDL.Variant({
    'info' : IDL.Null,
    'warn' : IDL.Null,
    'error' : IDL.Null,
  }),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'callId' : IDL.Opt(IDL.Nat),
});
export const CallStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const CallRecordPublic = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : CallStatus,
  'endTime' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'recipientPhone' : IDL.Text,
  'callSid' : IDL.Opt(IDL.Text),
  'presetId' : IDL.Nat,
  'transcript' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TwilioLine = IDL.Record({
  'enabled' : IDL.Bool,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const TwilioLineInput = IDL.Record({
  'enabled' : IDL.Bool,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const TwilioLineMutationResult = IDL.Variant({
  'ok' : IDL.Vec(TwilioLine),
  'err' : IDL.Text,
});
export const ToolsEnabled = IDL.Record({
  'xSearch' : IDL.Bool,
  'webSearch' : IDL.Bool,
  'functionCalling' : IDL.Bool,
});
export const Voice = IDL.Variant({
  'ara' : IDL.Null,
  'eve' : IDL.Null,
  'leo' : IDL.Null,
  'rex' : IDL.Null,
  'sal' : IDL.Null,
});
export const SampleRate = IDL.Variant({
  'hz16000' : IDL.Null,
  'hz32000' : IDL.Null,
  'hz22050' : IDL.Null,
  'hz24000' : IDL.Null,
  'hz44100' : IDL.Null,
  'hz48000' : IDL.Null,
  'hz8000' : IDL.Null,
});
export const TurnDetection = IDL.Record({
  'prefixPaddingMs' : IDL.Nat,
  'threshold' : IDL.Float64,
  'silenceDurationMs' : IDL.Nat,
  'serverVad' : IDL.Bool,
});
export const AudioFormat = IDL.Variant({
  'pcm' : IDL.Null,
  'pcma' : IDL.Null,
  'pcmu' : IDL.Null,
});
export const CallPresetInput = IDL.Record({
  'toolsEnabled' : ToolsEnabled,
  'voice' : Voice,
  'voiceId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'sampleRate' : SampleRate,
  'systemPrompt' : IDL.Text,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
});
export const CallPreset = IDL.Record({
  'id' : IDL.Nat,
  'toolsEnabled' : ToolsEnabled,
  'ownerId' : IDL.Principal,
  'voice' : Voice,
  'voiceId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'sampleRate' : SampleRate,
  'systemPrompt' : IDL.Text,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
});
export const CallPresetMutationResult = IDL.Variant({
  'ok' : CallPreset,
  'err' : IDL.Text,
});
export const AnsweringPresetStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'verified' : IDL.Null,
});
export const AnsweringCaptureOptions = IDL.Record({
  'saveTranscript' : IDL.Bool,
  'recordAudio' : IDL.Bool,
  'consentConfirmed' : IDL.Bool,
});
export const AnsweringPreset = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'systemPrompt' : IDL.Text,
  'voice' : Voice,
  'voiceId' : IDL.Opt(IDL.Text),
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
  'sampleRate' : SampleRate,
  'toolsEnabled' : ToolsEnabled,
  'captureOptions' : AnsweringCaptureOptions,
  'enabled' : IDL.Bool,
  'verificationStatus' : AnsweringPresetStatus,
  'webhookSecret' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'verifiedAt' : IDL.Opt(IDL.Int),
  'lastIncomingAt' : IDL.Opt(IDL.Int),
});
export const AnsweringPresetInput = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'systemPrompt' : IDL.Text,
  'voice' : Voice,
  'voiceId' : IDL.Opt(IDL.Text),
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
  'sampleRate' : SampleRate,
  'toolsEnabled' : ToolsEnabled,
  'captureOptions' : AnsweringCaptureOptions,
  'enabled' : IDL.Bool,
  'webhookSecret' : IDL.Text,
});
export const AnsweringPresetMutationResult = IDL.Variant({
  'ok' : AnsweringPreset,
  'err' : IDL.Text,
});
export const AnsweringLiveSession = IDL.Record({
  'sessionId' : IDL.Text,
  'monitorToken' : IDL.Text,
  'callSid' : IDL.Text,
  'userId' : IDL.Principal,
  'answeringPresetId' : IDL.Nat,
  'answeringPresetName' : IDL.Text,
  'callerPhone' : IDL.Text,
  'startedAt' : IDL.Int,
  'allowedSeconds' : IDL.Nat,
});
export const PresetId = IDL.Nat;
export const CallId = IDL.Nat;
export const InitiateCallInput = IDL.Record({
  'recipientPhone' : IDL.Text,
  'presetId' : IDL.Nat,
});
export const InitiateCallResult = IDL.Variant({
  'ok' : IDL.Record({ 'callSid' : IDL.Text, 'callId' : IDL.Nat }),
  'err' : IDL.Text,
});
export const StripeMode = IDL.Variant({
  'live' : IDL.Null,
  'test' : IDL.Null,
});
export const PurchaseIntentStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'paid' : IDL.Null,
  'pending' : IDL.Null,
});
export const PurchaseIntentPublic = IDL.Record({
  'amountCents' : IDL.Nat,
  'createdAt' : IDL.Int,
  'id' : IDL.Text,
  'mode' : StripeMode,
  'packageId' : IDL.Text,
  'paidAt' : IDL.Opt(IDL.Int),
  'seconds' : IDL.Nat,
  'status' : PurchaseIntentStatus,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
});
export const CreatePurchaseIntentResult = IDL.Variant({
  'ok' : PurchaseIntentPublic,
  'err' : IDL.Text,
});
export const CallReservationStatus = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'finished' : IDL.Null,
  'reserved' : IDL.Null,
});
export const CallReservationPublic = IDL.Record({
  'allowedSeconds' : IDL.Nat,
  'billedSeconds' : IDL.Opt(IDL.Nat),
  'callId' : IDL.Nat,
  'callSid' : IDL.Opt(IDL.Text),
  'callToken' : IDL.Opt(IDL.Text),
  'canceledReason' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'expiresAt' : IDL.Int,
  'finishedAt' : IDL.Opt(IDL.Int),
  'id' : IDL.Text,
  'presetId' : IDL.Nat,
  'recipientPhone' : IDL.Text,
  'startedAt' : IDL.Opt(IDL.Int),
  'status' : CallReservationStatus,
  'transcript' : IDL.Opt(IDL.Text),
  'usedSeconds' : IDL.Opt(IDL.Nat),
  'user' : IDL.Principal,
});
export const ReserveCallResult = IDL.Variant({
  'ok' : CallReservationPublic,
  'err' : IDL.Text,
});
export const BillingPackage = IDL.Record({
  'amountCents' : IDL.Nat,
  'id' : IDL.Text,
  'name' : IDL.Text,
  'seconds' : IDL.Nat,
});
export const BillingStatus = IDL.Record({
  'availableSeconds' : IDL.Nat,
  'balanceSeconds' : IDL.Nat,
  'packages' : IDL.Vec(BillingPackage),
  'reservedSeconds' : IDL.Nat,
});
export const BillingMutationResult = IDL.Variant({
  'ok' : IDL.Bool,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminAddPromoMinutes' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [BillingMutationResult],
      [],
    ),
  'adminGetSystemLogs' : IDL.Func([IDL.Nat], [IDL.Vec(SystemLog)], ['query']),
  'adminListAllCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
  'adminListUserCalls' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CallRecordPublic)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelCallReservation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BillingMutationResult],
      [],
    ),
  'cancelCallReservationByCallSidForServer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BillingMutationResult],
      [],
    ),
  'createAnsweringPreset' : IDL.Func(
      [AnsweringPresetInput],
      [AnsweringPresetMutationResult],
      [],
    ),
  'createPreset' : IDL.Func([CallPresetInput], [CallPreset], []),
  'createPurchaseIntent' : IDL.Func(
      [IDL.Text],
      [CreatePurchaseIntentResult],
      [],
    ),
  'creditPaidSeconds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, StripeMode],
      [BillingMutationResult],
      [],
    ),
  'deleteAnsweringPreset' : IDL.Func([PresetId], [IDL.Bool], []),
  'deletePreset' : IDL.Func([PresetId], [IDL.Bool], []),
  'duplicatePreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], []),
  'extendCallReservationForServer' : IDL.Func(
      [IDL.Text],
      [ReserveCallResult],
      [],
    ),
  'finishCallAndDebit' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [BillingMutationResult],
      [],
    ),
  'finishCallByCallSidForServer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [BillingMutationResult],
      [],
    ),
  'getAdminConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'hasXaiKey' : IDL.Bool,
          'hasTwilioAuth' : IDL.Bool,
          'twilioFromNumber' : IDL.Text,
          'twilioAccountSid' : IDL.Text,
          'twilioPhoneNumbers' : IDL.Vec(TwilioLine),
        }),
      ],
      ['query'],
    ),
  'getCallRecord' : IDL.Func([CallId], [IDL.Opt(CallRecordPublic)], ['query']),
  'getBillingPackages' : IDL.Func([], [IDL.Vec(BillingPackage)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getAnsweringPreset' : IDL.Func(
      [PresetId],
      [IDL.Opt(AnsweringPreset)],
      ['query'],
    ),
  'getMyBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
  'getPreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], ['query']),
  'getPresetForServer' : IDL.Func(
      [PresetId],
      [IDL.Opt(CallPreset)],
      ['query'],
    ),
  'getPurchaseIntentForServer' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PurchaseIntentPublic)],
      ['query'],
    ),
  'getTwilioLineNumbersForServer' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAnsweringPresetForServer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(AnsweringPreset)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([InitiateCallInput], [InitiateCallResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyAnsweringLiveSessions' : IDL.Func(
      [],
      [IDL.Vec(AnsweringLiveSession)],
      ['query'],
    ),
  'listMyAnsweringPresets' : IDL.Func(
      [],
      [IDL.Vec(AnsweringPreset)],
      ['query'],
    ),
  'listMyCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
  'listMyPresets' : IDL.Func([], [IDL.Vec(CallPreset)], ['query']),
  'listOpenCallReservationsForServer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CallReservationPublic)],
      ['query'],
    ),
  'markReservationStarted' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BillingMutationResult],
      [],
    ),
  'removeTwilioLine' : IDL.Func(
      [IDL.Text],
      [TwilioLineMutationResult],
      [],
    ),
  'reserveCall' : IDL.Func([InitiateCallInput], [ReserveCallResult], []),
  'reserveIncomingAnsweringCall' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ReserveCallResult],
      [],
    ),
  'setAdminConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setAnsweringPresetEnabled' : IDL.Func(
      [PresetId, IDL.Bool],
      [AnsweringPresetMutationResult],
      [],
    ),
  'setTwilioLine' : IDL.Func(
      [TwilioLineInput],
      [TwilioLineMutationResult],
      [],
    ),
  'setTwilioLineEnabled' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [TwilioLineMutationResult],
      [],
    ),
  'twilioWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateCallStatus' : IDL.Func(
      [CallId, CallStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateAnsweringPreset' : IDL.Func(
      [PresetId, AnsweringPresetInput],
      [AnsweringPresetMutationResult],
      [],
    ),
  'updateAnsweringPresetInstructions' : IDL.Func(
      [PresetId, IDL.Text],
      [AnsweringPresetMutationResult],
      [],
    ),
  'updatePreset' : IDL.Func(
      [PresetId, CallPresetInput],
      [IDL.Opt(CallPreset)],
      [],
    ),
  'updatePresetInstructions' : IDL.Func(
      [PresetId, IDL.Text],
      [CallPresetMutationResult],
      [],
    ),
  'verifyAnsweringPresetForServer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [AnsweringPresetMutationResult],
      [],
    ),
  'registerAnsweringLiveSessionForServer' : IDL.Func(
      [AnsweringLiveSession],
      [IDL.Bool],
      [],
    ),
  'finishAnsweringLiveSessionForServer' : IDL.Func(
      [IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SystemLog = IDL.Record({
    'level' : IDL.Variant({
      'info' : IDL.Null,
      'warn' : IDL.Null,
      'error' : IDL.Null,
    }),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'callId' : IDL.Opt(IDL.Nat),
  });
  const CallStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CallRecordPublic = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : CallStatus,
    'endTime' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'recipientPhone' : IDL.Text,
    'callSid' : IDL.Opt(IDL.Text),
    'presetId' : IDL.Nat,
    'transcript' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TwilioLine = IDL.Record({
    'enabled' : IDL.Bool,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const TwilioLineInput = IDL.Record({
    'enabled' : IDL.Bool,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const TwilioLineMutationResult = IDL.Variant({
    'ok' : IDL.Vec(TwilioLine),
    'err' : IDL.Text,
  });
  const ToolsEnabled = IDL.Record({
    'xSearch' : IDL.Bool,
    'webSearch' : IDL.Bool,
    'functionCalling' : IDL.Bool,
  });
  const Voice = IDL.Variant({
    'ara' : IDL.Null,
    'eve' : IDL.Null,
    'leo' : IDL.Null,
    'rex' : IDL.Null,
    'sal' : IDL.Null,
  });
  const SampleRate = IDL.Variant({
    'hz16000' : IDL.Null,
    'hz32000' : IDL.Null,
    'hz22050' : IDL.Null,
    'hz24000' : IDL.Null,
    'hz44100' : IDL.Null,
    'hz48000' : IDL.Null,
    'hz8000' : IDL.Null,
  });
  const TurnDetection = IDL.Record({
    'prefixPaddingMs' : IDL.Nat,
    'threshold' : IDL.Float64,
    'silenceDurationMs' : IDL.Nat,
    'serverVad' : IDL.Bool,
  });
  const AudioFormat = IDL.Variant({
    'pcm' : IDL.Null,
    'pcma' : IDL.Null,
    'pcmu' : IDL.Null,
  });
  const CallPresetInput = IDL.Record({
    'toolsEnabled' : ToolsEnabled,
    'voice' : Voice,
    'voiceId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'sampleRate' : SampleRate,
    'systemPrompt' : IDL.Text,
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
  });
  const CallPreset = IDL.Record({
    'id' : IDL.Nat,
    'toolsEnabled' : ToolsEnabled,
    'ownerId' : IDL.Principal,
    'voice' : Voice,
    'voiceId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'sampleRate' : SampleRate,
    'systemPrompt' : IDL.Text,
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
  });
  const CallPresetMutationResult = IDL.Variant({
    'ok' : CallPreset,
    'err' : IDL.Text,
  });
  const AnsweringPresetStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'verified' : IDL.Null,
  });
  const AnsweringCaptureOptions = IDL.Record({
    'saveTranscript' : IDL.Bool,
    'recordAudio' : IDL.Bool,
    'consentConfirmed' : IDL.Bool,
  });
  const AnsweringPreset = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'systemPrompt' : IDL.Text,
    'voice' : Voice,
    'voiceId' : IDL.Opt(IDL.Text),
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
    'sampleRate' : SampleRate,
    'toolsEnabled' : ToolsEnabled,
    'captureOptions' : AnsweringCaptureOptions,
    'enabled' : IDL.Bool,
    'verificationStatus' : AnsweringPresetStatus,
    'webhookSecret' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'verifiedAt' : IDL.Opt(IDL.Int),
    'lastIncomingAt' : IDL.Opt(IDL.Int),
  });
  const AnsweringPresetInput = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'systemPrompt' : IDL.Text,
    'voice' : Voice,
    'voiceId' : IDL.Opt(IDL.Text),
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
    'sampleRate' : SampleRate,
    'toolsEnabled' : ToolsEnabled,
    'captureOptions' : AnsweringCaptureOptions,
    'enabled' : IDL.Bool,
    'webhookSecret' : IDL.Text,
  });
  const AnsweringPresetMutationResult = IDL.Variant({
    'ok' : AnsweringPreset,
    'err' : IDL.Text,
  });
  const AnsweringLiveSession = IDL.Record({
    'sessionId' : IDL.Text,
    'monitorToken' : IDL.Text,
    'callSid' : IDL.Text,
    'userId' : IDL.Principal,
    'answeringPresetId' : IDL.Nat,
    'answeringPresetName' : IDL.Text,
    'callerPhone' : IDL.Text,
    'startedAt' : IDL.Int,
    'allowedSeconds' : IDL.Nat,
  });
  const PresetId = IDL.Nat;
  const CallId = IDL.Nat;
  const InitiateCallInput = IDL.Record({
    'recipientPhone' : IDL.Text,
    'presetId' : IDL.Nat,
  });
  const InitiateCallResult = IDL.Variant({
    'ok' : IDL.Record({ 'callSid' : IDL.Text, 'callId' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const StripeMode = IDL.Variant({
    'live' : IDL.Null,
    'test' : IDL.Null,
  });
  const PurchaseIntentStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'paid' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PurchaseIntentPublic = IDL.Record({
    'amountCents' : IDL.Nat,
    'createdAt' : IDL.Int,
    'id' : IDL.Text,
    'mode' : StripeMode,
    'packageId' : IDL.Text,
    'paidAt' : IDL.Opt(IDL.Int),
    'seconds' : IDL.Nat,
    'status' : PurchaseIntentStatus,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
  });
  const CreatePurchaseIntentResult = IDL.Variant({
    'ok' : PurchaseIntentPublic,
    'err' : IDL.Text,
  });
  const CallReservationStatus = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'finished' : IDL.Null,
    'reserved' : IDL.Null,
  });
  const CallReservationPublic = IDL.Record({
    'allowedSeconds' : IDL.Nat,
    'billedSeconds' : IDL.Opt(IDL.Nat),
    'callId' : IDL.Nat,
    'callSid' : IDL.Opt(IDL.Text),
    'callToken' : IDL.Opt(IDL.Text),
    'canceledReason' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'expiresAt' : IDL.Int,
    'finishedAt' : IDL.Opt(IDL.Int),
    'id' : IDL.Text,
    'presetId' : IDL.Nat,
    'recipientPhone' : IDL.Text,
    'startedAt' : IDL.Opt(IDL.Int),
    'status' : CallReservationStatus,
    'transcript' : IDL.Opt(IDL.Text),
    'usedSeconds' : IDL.Opt(IDL.Nat),
    'user' : IDL.Principal,
  });
  const ReserveCallResult = IDL.Variant({
    'ok' : CallReservationPublic,
    'err' : IDL.Text,
  });
  const BillingPackage = IDL.Record({
    'amountCents' : IDL.Nat,
    'id' : IDL.Text,
    'name' : IDL.Text,
    'seconds' : IDL.Nat,
  });
  const BillingStatus = IDL.Record({
    'availableSeconds' : IDL.Nat,
    'balanceSeconds' : IDL.Nat,
    'packages' : IDL.Vec(BillingPackage),
    'reservedSeconds' : IDL.Nat,
  });
  const BillingMutationResult = IDL.Variant({
    'ok' : IDL.Bool,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminAddPromoMinutes' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [BillingMutationResult],
        [],
      ),
    'adminGetSystemLogs' : IDL.Func([IDL.Nat], [IDL.Vec(SystemLog)], ['query']),
    'adminListAllCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
    'adminListUserCalls' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CallRecordPublic)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelCallReservation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingMutationResult],
        [],
      ),
    'cancelCallReservationByCallSidForServer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingMutationResult],
        [],
      ),
    'createAnsweringPreset' : IDL.Func(
        [AnsweringPresetInput],
        [AnsweringPresetMutationResult],
        [],
      ),
    'createPreset' : IDL.Func([CallPresetInput], [CallPreset], []),
    'createPurchaseIntent' : IDL.Func(
        [IDL.Text],
        [CreatePurchaseIntentResult],
        [],
      ),
    'creditPaidSeconds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, StripeMode],
        [BillingMutationResult],
        [],
      ),
    'deleteAnsweringPreset' : IDL.Func([PresetId], [IDL.Bool], []),
    'deletePreset' : IDL.Func([PresetId], [IDL.Bool], []),
    'duplicatePreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], []),
    'extendCallReservationForServer' : IDL.Func(
        [IDL.Text],
        [ReserveCallResult],
        [],
      ),
    'finishCallAndDebit' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [BillingMutationResult],
        [],
      ),
    'finishCallByCallSidForServer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [BillingMutationResult],
        [],
      ),
    'getAdminConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'hasXaiKey' : IDL.Bool,
            'hasTwilioAuth' : IDL.Bool,
            'twilioFromNumber' : IDL.Text,
            'twilioAccountSid' : IDL.Text,
            'twilioPhoneNumbers' : IDL.Vec(TwilioLine),
          }),
        ],
        ['query'],
      ),
    'getCallRecord' : IDL.Func(
        [CallId],
        [IDL.Opt(CallRecordPublic)],
        ['query'],
    ),
    'getBillingPackages' : IDL.Func([], [IDL.Vec(BillingPackage)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getAnsweringPreset' : IDL.Func(
        [PresetId],
        [IDL.Opt(AnsweringPreset)],
        ['query'],
      ),
    'getMyBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
    'getPreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], ['query']),
    'getPresetForServer' : IDL.Func(
        [PresetId],
        [IDL.Opt(CallPreset)],
        ['query'],
      ),
    'getPurchaseIntentForServer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PurchaseIntentPublic)],
        ['query'],
      ),
    'getTwilioLineNumbersForServer' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAnsweringPresetForServer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(AnsweringPreset)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([InitiateCallInput], [InitiateCallResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyAnsweringLiveSessions' : IDL.Func(
        [],
        [IDL.Vec(AnsweringLiveSession)],
        ['query'],
      ),
    'listMyAnsweringPresets' : IDL.Func(
        [],
        [IDL.Vec(AnsweringPreset)],
        ['query'],
      ),
    'listMyCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
    'listMyPresets' : IDL.Func([], [IDL.Vec(CallPreset)], ['query']),
    'listOpenCallReservationsForServer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CallReservationPublic)],
        ['query'],
      ),
    'markReservationStarted' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingMutationResult],
        [],
      ),
    'removeTwilioLine' : IDL.Func(
        [IDL.Text],
        [TwilioLineMutationResult],
        [],
      ),
    'reserveCall' : IDL.Func([InitiateCallInput], [ReserveCallResult], []),
    'reserveIncomingAnsweringCall' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ReserveCallResult],
        [],
      ),
    'setAdminConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setAnsweringPresetEnabled' : IDL.Func(
        [PresetId, IDL.Bool],
        [AnsweringPresetMutationResult],
        [],
      ),
    'setTwilioLine' : IDL.Func(
        [TwilioLineInput],
        [TwilioLineMutationResult],
        [],
      ),
    'setTwilioLineEnabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [TwilioLineMutationResult],
        [],
      ),
    'twilioWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateCallStatus' : IDL.Func(
        [CallId, CallStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateAnsweringPreset' : IDL.Func(
        [PresetId, AnsweringPresetInput],
        [AnsweringPresetMutationResult],
        [],
      ),
    'updateAnsweringPresetInstructions' : IDL.Func(
        [PresetId, IDL.Text],
        [AnsweringPresetMutationResult],
        [],
      ),
    'updatePreset' : IDL.Func(
        [PresetId, CallPresetInput],
        [IDL.Opt(CallPreset)],
        [],
      ),
    'updatePresetInstructions' : IDL.Func(
        [PresetId, IDL.Text],
        [CallPresetMutationResult],
        [],
      ),
    'verifyAnsweringPresetForServer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [AnsweringPresetMutationResult],
        [],
      ),
    'registerAnsweringLiveSessionForServer' : IDL.Func(
        [AnsweringLiveSession],
        [IDL.Bool],
        [],
      ),
    'finishAnsweringLiveSessionForServer' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
