/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SystemLog = IDL.Record({
  'level' : IDL.Variant({
    'info' : IDL.Null,
    'warn' : IDL.Null,
    'error' : IDL.Null,
  }),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'callId' : IDL.Opt(IDL.Nat),
});
export const CallStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const CallRecordPublic = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : CallStatus,
  'endTime' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'recipientPhone' : IDL.Text,
  'callSid' : IDL.Opt(IDL.Text),
  'presetId' : IDL.Nat,
  'transcript' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ToolsEnabled = IDL.Record({
  'xSearch' : IDL.Bool,
  'webSearch' : IDL.Bool,
  'functionCalling' : IDL.Bool,
});
export const Voice = IDL.Variant({
  'ara' : IDL.Null,
  'eve' : IDL.Null,
  'leo' : IDL.Null,
  'rex' : IDL.Null,
  'sal' : IDL.Null,
});
export const SampleRate = IDL.Variant({
  'hz16000' : IDL.Null,
  'hz32000' : IDL.Null,
  'hz22050' : IDL.Null,
  'hz24000' : IDL.Null,
  'hz44100' : IDL.Null,
  'hz48000' : IDL.Null,
  'hz8000' : IDL.Null,
});
export const TurnDetection = IDL.Record({
  'prefixPaddingMs' : IDL.Nat,
  'threshold' : IDL.Float64,
  'silenceDurationMs' : IDL.Nat,
  'serverVad' : IDL.Bool,
});
export const AudioFormat = IDL.Variant({
  'pcm' : IDL.Null,
  'pcma' : IDL.Null,
  'pcmu' : IDL.Null,
});
export const CallPresetInput = IDL.Record({
  'toolsEnabled' : ToolsEnabled,
  'voice' : Voice,
  'name' : IDL.Text,
  'sampleRate' : SampleRate,
  'systemPrompt' : IDL.Text,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
});
export const CallPreset = IDL.Record({
  'id' : IDL.Nat,
  'toolsEnabled' : ToolsEnabled,
  'ownerId' : IDL.Principal,
  'voice' : Voice,
  'name' : IDL.Text,
  'sampleRate' : SampleRate,
  'systemPrompt' : IDL.Text,
  'turnDetection' : TurnDetection,
  'audioFormat' : AudioFormat,
});
export const PresetId = IDL.Nat;
export const CallId = IDL.Nat;
export const EphemeralTokenResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'websocketUrl' : IDL.Text }),
  'err' : IDL.Text,
});
export const InitiateCallInput = IDL.Record({
  'recipientPhone' : IDL.Text,
  'presetId' : IDL.Nat,
});
export const InitiateCallResult = IDL.Variant({
  'ok' : IDL.Record({ 'callSid' : IDL.Text, 'callId' : IDL.Nat }),
  'err' : IDL.Text,
});
export const StripeMode = IDL.Variant({
  'live' : IDL.Null,
  'test' : IDL.Null,
});
export const PurchaseIntentStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'paid' : IDL.Null,
  'pending' : IDL.Null,
});
export const PurchaseIntentPublic = IDL.Record({
  'amountCents' : IDL.Nat,
  'createdAt' : IDL.Int,
  'id' : IDL.Text,
  'mode' : StripeMode,
  'packageId' : IDL.Text,
  'paidAt' : IDL.Opt(IDL.Int),
  'seconds' : IDL.Nat,
  'status' : PurchaseIntentStatus,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
});
export const CreatePurchaseIntentResult = IDL.Variant({
  'ok' : PurchaseIntentPublic,
  'err' : IDL.Text,
});
export const CallReservationStatus = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'finished' : IDL.Null,
  'reserved' : IDL.Null,
});
export const CallReservationPublic = IDL.Record({
  'allowedSeconds' : IDL.Nat,
  'billedSeconds' : IDL.Opt(IDL.Nat),
  'callId' : IDL.Nat,
  'callSid' : IDL.Opt(IDL.Text),
  'callToken' : IDL.Opt(IDL.Text),
  'canceledReason' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'expiresAt' : IDL.Int,
  'finishedAt' : IDL.Opt(IDL.Int),
  'id' : IDL.Text,
  'presetId' : IDL.Nat,
  'recipientPhone' : IDL.Text,
  'startedAt' : IDL.Opt(IDL.Int),
  'status' : CallReservationStatus,
  'transcript' : IDL.Opt(IDL.Text),
  'usedSeconds' : IDL.Opt(IDL.Nat),
  'user' : IDL.Principal,
});
export const ReserveCallResult = IDL.Variant({
  'ok' : CallReservationPublic,
  'err' : IDL.Text,
});
export const BillingPackage = IDL.Record({
  'amountCents' : IDL.Nat,
  'id' : IDL.Text,
  'name' : IDL.Text,
  'seconds' : IDL.Nat,
});
export const BillingStatus = IDL.Record({
  'availableSeconds' : IDL.Nat,
  'balanceSeconds' : IDL.Nat,
  'packages' : IDL.Vec(BillingPackage),
  'reservedSeconds' : IDL.Nat,
});
export const BillingMutationResult = IDL.Variant({
  'ok' : IDL.Bool,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminAddPromoMinutes' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [BillingMutationResult],
      [],
    ),
  'adminGetSystemLogs' : IDL.Func([IDL.Nat], [IDL.Vec(SystemLog)], ['query']),
  'adminListAllCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
  'adminListUserCalls' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CallRecordPublic)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelCallReservation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BillingMutationResult],
      [],
    ),
  'createPreset' : IDL.Func([CallPresetInput], [CallPreset], []),
  'createPurchaseIntent' : IDL.Func(
      [IDL.Text],
      [CreatePurchaseIntentResult],
      [],
    ),
  'creditPaidSeconds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, StripeMode],
      [BillingMutationResult],
      [],
    ),
  'deletePreset' : IDL.Func([PresetId], [IDL.Bool], []),
  'duplicatePreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], []),
  'finishCallAndDebit' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [BillingMutationResult],
      [],
    ),
  'getAdminConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'hasXaiKey' : IDL.Bool,
          'hasTwilioAuth' : IDL.Bool,
          'twilioFromNumber' : IDL.Text,
          'twilioAccountSid' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCallRecord' : IDL.Func([CallId], [IDL.Opt(CallRecordPublic)], ['query']),
  'getBillingPackages' : IDL.Func([], [IDL.Vec(BillingPackage)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEphemeralToken' : IDL.Func([PresetId], [EphemeralTokenResult], []),
  'getMyBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
  'getPreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], ['query']),
  'getPurchaseIntentForServer' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PurchaseIntentPublic)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([InitiateCallInput], [InitiateCallResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
  'listMyPresets' : IDL.Func([], [IDL.Vec(CallPreset)], ['query']),
  'markReservationStarted' : IDL.Func(
      [IDL.Text, IDL.Text],
      [BillingMutationResult],
      [],
    ),
  'reserveCall' : IDL.Func([InitiateCallInput], [ReserveCallResult], []),
  'setAdminConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'twilioWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateCallStatus' : IDL.Func(
      [CallId, CallStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updatePreset' : IDL.Func(
      [PresetId, CallPresetInput],
      [IDL.Opt(CallPreset)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SystemLog = IDL.Record({
    'level' : IDL.Variant({
      'info' : IDL.Null,
      'warn' : IDL.Null,
      'error' : IDL.Null,
    }),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'callId' : IDL.Opt(IDL.Nat),
  });
  const CallStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CallRecordPublic = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : CallStatus,
    'endTime' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'recipientPhone' : IDL.Text,
    'callSid' : IDL.Opt(IDL.Text),
    'presetId' : IDL.Nat,
    'transcript' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ToolsEnabled = IDL.Record({
    'xSearch' : IDL.Bool,
    'webSearch' : IDL.Bool,
    'functionCalling' : IDL.Bool,
  });
  const Voice = IDL.Variant({
    'ara' : IDL.Null,
    'eve' : IDL.Null,
    'leo' : IDL.Null,
    'rex' : IDL.Null,
    'sal' : IDL.Null,
  });
  const SampleRate = IDL.Variant({
    'hz16000' : IDL.Null,
    'hz32000' : IDL.Null,
    'hz22050' : IDL.Null,
    'hz24000' : IDL.Null,
    'hz44100' : IDL.Null,
    'hz48000' : IDL.Null,
    'hz8000' : IDL.Null,
  });
  const TurnDetection = IDL.Record({
    'prefixPaddingMs' : IDL.Nat,
    'threshold' : IDL.Float64,
    'silenceDurationMs' : IDL.Nat,
    'serverVad' : IDL.Bool,
  });
  const AudioFormat = IDL.Variant({
    'pcm' : IDL.Null,
    'pcma' : IDL.Null,
    'pcmu' : IDL.Null,
  });
  const CallPresetInput = IDL.Record({
    'toolsEnabled' : ToolsEnabled,
    'voice' : Voice,
    'name' : IDL.Text,
    'sampleRate' : SampleRate,
    'systemPrompt' : IDL.Text,
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
  });
  const CallPreset = IDL.Record({
    'id' : IDL.Nat,
    'toolsEnabled' : ToolsEnabled,
    'ownerId' : IDL.Principal,
    'voice' : Voice,
    'name' : IDL.Text,
    'sampleRate' : SampleRate,
    'systemPrompt' : IDL.Text,
    'turnDetection' : TurnDetection,
    'audioFormat' : AudioFormat,
  });
  const PresetId = IDL.Nat;
  const CallId = IDL.Nat;
  const EphemeralTokenResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'websocketUrl' : IDL.Text }),
    'err' : IDL.Text,
  });
  const InitiateCallInput = IDL.Record({
    'recipientPhone' : IDL.Text,
    'presetId' : IDL.Nat,
  });
  const InitiateCallResult = IDL.Variant({
    'ok' : IDL.Record({ 'callSid' : IDL.Text, 'callId' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const StripeMode = IDL.Variant({
    'live' : IDL.Null,
    'test' : IDL.Null,
  });
  const PurchaseIntentStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'paid' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PurchaseIntentPublic = IDL.Record({
    'amountCents' : IDL.Nat,
    'createdAt' : IDL.Int,
    'id' : IDL.Text,
    'mode' : StripeMode,
    'packageId' : IDL.Text,
    'paidAt' : IDL.Opt(IDL.Int),
    'seconds' : IDL.Nat,
    'status' : PurchaseIntentStatus,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
  });
  const CreatePurchaseIntentResult = IDL.Variant({
    'ok' : PurchaseIntentPublic,
    'err' : IDL.Text,
  });
  const CallReservationStatus = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'finished' : IDL.Null,
    'reserved' : IDL.Null,
  });
  const CallReservationPublic = IDL.Record({
    'allowedSeconds' : IDL.Nat,
    'billedSeconds' : IDL.Opt(IDL.Nat),
    'callId' : IDL.Nat,
    'callSid' : IDL.Opt(IDL.Text),
    'callToken' : IDL.Opt(IDL.Text),
    'canceledReason' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'expiresAt' : IDL.Int,
    'finishedAt' : IDL.Opt(IDL.Int),
    'id' : IDL.Text,
    'presetId' : IDL.Nat,
    'recipientPhone' : IDL.Text,
    'startedAt' : IDL.Opt(IDL.Int),
    'status' : CallReservationStatus,
    'transcript' : IDL.Opt(IDL.Text),
    'usedSeconds' : IDL.Opt(IDL.Nat),
    'user' : IDL.Principal,
  });
  const ReserveCallResult = IDL.Variant({
    'ok' : CallReservationPublic,
    'err' : IDL.Text,
  });
  const BillingPackage = IDL.Record({
    'amountCents' : IDL.Nat,
    'id' : IDL.Text,
    'name' : IDL.Text,
    'seconds' : IDL.Nat,
  });
  const BillingStatus = IDL.Record({
    'availableSeconds' : IDL.Nat,
    'balanceSeconds' : IDL.Nat,
    'packages' : IDL.Vec(BillingPackage),
    'reservedSeconds' : IDL.Nat,
  });
  const BillingMutationResult = IDL.Variant({
    'ok' : IDL.Bool,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminAddPromoMinutes' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [BillingMutationResult],
        [],
      ),
    'adminGetSystemLogs' : IDL.Func([IDL.Nat], [IDL.Vec(SystemLog)], ['query']),
    'adminListAllCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
    'adminListUserCalls' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CallRecordPublic)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelCallReservation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingMutationResult],
        [],
      ),
    'createPreset' : IDL.Func([CallPresetInput], [CallPreset], []),
    'createPurchaseIntent' : IDL.Func(
        [IDL.Text],
        [CreatePurchaseIntentResult],
        [],
      ),
    'creditPaidSeconds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Nat, StripeMode],
        [BillingMutationResult],
        [],
      ),
    'deletePreset' : IDL.Func([PresetId], [IDL.Bool], []),
    'duplicatePreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], []),
    'finishCallAndDebit' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [BillingMutationResult],
        [],
      ),
    'getAdminConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'hasXaiKey' : IDL.Bool,
            'hasTwilioAuth' : IDL.Bool,
            'twilioFromNumber' : IDL.Text,
            'twilioAccountSid' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCallRecord' : IDL.Func(
        [CallId],
        [IDL.Opt(CallRecordPublic)],
        ['query'],
      ),
    'getBillingPackages' : IDL.Func([], [IDL.Vec(BillingPackage)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEphemeralToken' : IDL.Func([PresetId], [EphemeralTokenResult], []),
    'getMyBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
    'getPreset' : IDL.Func([PresetId], [IDL.Opt(CallPreset)], ['query']),
    'getPurchaseIntentForServer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PurchaseIntentPublic)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([InitiateCallInput], [InitiateCallResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
    'listMyPresets' : IDL.Func([], [IDL.Vec(CallPreset)], ['query']),
    'markReservationStarted' : IDL.Func(
        [IDL.Text, IDL.Text],
        [BillingMutationResult],
        [],
      ),
    'reserveCall' : IDL.Func([InitiateCallInput], [ReserveCallResult], []),
    'setAdminConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'twilioWebhook' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateCallStatus' : IDL.Func(
        [CallId, CallStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updatePreset' : IDL.Func(
        [PresetId, CallPresetInput],
        [IDL.Opt(CallPreset)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
